services:
  auth-gateway:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
      args:
        service: auth-gateway
    environment:
      PORT: 3000
    ports:
      - 8080:3000
      - 9229:9229
    command: pnpm nx serve auth-gateway --watch
    develop:
      watch:
        - action: sync
          path: ./apps/auth-gateway
          target: /usr/src/app/apps/auth-gateway
          ignore:
            - node_modules/
        - action: sync
          path: ./libs
          target: /usr/src/app/libs
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  notifications-gateway:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
      args:
        service: notifications-gateway
    environment:
      PORT: 3000
    ports:
      - 8081:3000
      - 9230:9229
    command: pnpm nx serve notifications-gateway --watch
    develop:
      watch:
        - action: sync
          path: ./apps/notifications-gateway
          target: /usr/src/app/apps/notifications-gateway
          ignore:
            - node_modules/
        - action: sync
          path: ./libs
          target: /usr/src/app/libs
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
